apiVersion: batch/v1
kind: Job
metadata:
  name: sbrit004-batch-job
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab
        command:
        - "wget"
        args:
        - "http://www.cs.ucr.edu/~vhill/index.html"
        resources:
          limits:
            memory: 48Gi
            cpu: "3"
          requests:
            memory: 4Gi
            cpu: "1"
      restartPolicy: Never
  backoffLimit: 5

