apiVersion: v1

kind: Pod
metadata:
  name: sbrit004-interactive-pod 
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /sbrit004-examplevol
      name: sbrit004-examplevol
    resources:
      limits:
        nvidia.com/gpu: 1
  volumes:
  - name: sbrit004-examplevol
    persistentVolumeClaim:
      claimName: sbrit004-examplevol

