apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: sbrit004-examplevol
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

